# Generated by Django 6.0.4 on 2026-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
